package com.example.msp.database.mapper;

import com.example.msp.database.entity.Users;
import com.example.msp.database.entity.UsersExample.Criteria;
import com.example.msp.database.entity.UsersExample.Criterion;
import com.example.msp.database.entity.UsersExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class UsersSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Thu May 25 11:57:55 MMT 2017
     */
    public String countByExample(UsersExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("\"users\"");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Thu May 25 11:57:55 MMT 2017
     */
    public String deleteByExample(UsersExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("\"users\"");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Thu May 25 11:57:55 MMT 2017
     */
    public String insertSelective(Users record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("\"users\"");
        
        if (record.getId() != null) {
            sql.VALUES("\"id\"", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getContent() != null) {
            sql.VALUES("\"content\"", "#{content,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            sql.VALUES("\"user_name\"", "#{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            sql.VALUES("\"email\"", "#{email,jdbcType=VARCHAR}");
        }
        
        if (record.getGender() != null) {
            sql.VALUES("\"gender\"", "#{gender,jdbcType=VARCHAR}");
        }
        
        if (record.getAge() != null) {
            sql.VALUES("\"age\"", "#{age,jdbcType=INTEGER}");
        }
        
        if (record.getCreatedDate() != null) {
            sql.VALUES("\"created_date\"", "#{createdDate,jdbcType=DATE}");
        }
        
        if (record.getUpdatedDate() != null) {
            sql.VALUES("\"updated_date\"", "#{updatedDate,jdbcType=DATE}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Thu May 25 11:57:55 MMT 2017
     */
    public String selectByExample(UsersExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("\"id\"");
        } else {
            sql.SELECT("\"id\"");
        }
        sql.SELECT("\"content\"");
        sql.SELECT("\"user_name\"");
        sql.SELECT("\"email\"");
        sql.SELECT("\"gender\"");
        sql.SELECT("\"age\"");
        sql.SELECT("\"created_date\"");
        sql.SELECT("\"updated_date\"");
        sql.FROM("\"users\"");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Thu May 25 11:57:55 MMT 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Users record = (Users) parameter.get("record");
        UsersExample example = (UsersExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("\"users\"");
        
        if (record.getId() != null) {
            sql.SET("\"id\" = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getContent() != null) {
            sql.SET("\"content\" = #{record.content,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            sql.SET("\"user_name\" = #{record.userName,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            sql.SET("\"email\" = #{record.email,jdbcType=VARCHAR}");
        }
        
        if (record.getGender() != null) {
            sql.SET("\"gender\" = #{record.gender,jdbcType=VARCHAR}");
        }
        
        if (record.getAge() != null) {
            sql.SET("\"age\" = #{record.age,jdbcType=INTEGER}");
        }
        
        if (record.getCreatedDate() != null) {
            sql.SET("\"created_date\" = #{record.createdDate,jdbcType=DATE}");
        }
        
        if (record.getUpdatedDate() != null) {
            sql.SET("\"updated_date\" = #{record.updatedDate,jdbcType=DATE}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Thu May 25 11:57:55 MMT 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("\"users\"");
        
        sql.SET("\"id\" = #{record.id,jdbcType=INTEGER}");
        sql.SET("\"content\" = #{record.content,jdbcType=VARCHAR}");
        sql.SET("\"user_name\" = #{record.userName,jdbcType=VARCHAR}");
        sql.SET("\"email\" = #{record.email,jdbcType=VARCHAR}");
        sql.SET("\"gender\" = #{record.gender,jdbcType=VARCHAR}");
        sql.SET("\"age\" = #{record.age,jdbcType=INTEGER}");
        sql.SET("\"created_date\" = #{record.createdDate,jdbcType=DATE}");
        sql.SET("\"updated_date\" = #{record.updatedDate,jdbcType=DATE}");
        
        UsersExample example = (UsersExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Thu May 25 11:57:55 MMT 2017
     */
    public String updateByPrimaryKeySelective(Users record) {
        SQL sql = new SQL();
        sql.UPDATE("\"users\"");
        
        if (record.getContent() != null) {
            sql.SET("\"content\" = #{content,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            sql.SET("\"user_name\" = #{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            sql.SET("\"email\" = #{email,jdbcType=VARCHAR}");
        }
        
        if (record.getGender() != null) {
            sql.SET("\"gender\" = #{gender,jdbcType=VARCHAR}");
        }
        
        if (record.getAge() != null) {
            sql.SET("\"age\" = #{age,jdbcType=INTEGER}");
        }
        
        if (record.getCreatedDate() != null) {
            sql.SET("\"created_date\" = #{createdDate,jdbcType=DATE}");
        }
        
        if (record.getUpdatedDate() != null) {
            sql.SET("\"updated_date\" = #{updatedDate,jdbcType=DATE}");
        }
        
        sql.WHERE("\"id\" = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Thu May 25 11:57:55 MMT 2017
     */
    protected void applyWhere(SQL sql, UsersExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}